### ISSUE TITLE
fd/ff/fdir does not return results but hangs on "loading"

### ISSUE THREAD

**Issue by dalanicolai** [brpaz/ulauncher-file-search#2]
fd/ff/fdir command does not return any results but instead hangs on loading (see image in attachment). Tried it on fedora 28 and ubuntu 18.04 (both had fd installed correctly and ulauncher restarted).

![screenshot from 2018-12-08 13-51-11](https://user-images.githubusercontent.com/18429791/49686198-52eb1300-faf1-11e8-93ab-ccb6ee04f5ef.png)

**Comment by keypey** [comment]
Same here. Debian/stretch/9.6

**Comment by keypey** [comment]
`2018-12-14 15:42:35,146 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event KeywordQueryEvent to "com.github.brpaz.ulauncher-file-search"
com.github.brpaz.ulauncher-file-search | 2018-12-14 15:42:35,163 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Client.py", line 52, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/bruno/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-file-search/main.py", line 115, in on_event
    results = extension.search(query.strip(), file_type)
  File "/home/bruno/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-file-search/main.py", line 51, in search
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] Nie ma takiego pliku ani katalogu
2018-12-14 15:42:35,558 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 1 results
2018-12-14 15:42:35,755 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event KeywordQueryEvent to "com.github.brpaz.ulauncher-file-search"
com.github.brpaz.ulauncher-file-search | 2018-12-14 15:42:35,765 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Client.py", line 52, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/bruno/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-file-search/main.py", line 115, in on_event
    results = extension.search(query.strip(), file_type)
  File "/home/bruno/.cache/ulauncher_cache/extensions/com.github.brpaz.ulauncher-file-search/main.py", line 51, in search
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] Nie ma takiego pliku ani katalogu`

**Comment by keypey** [comment]
Using the "jump" extension:
`2018-12-14 15:53:31,027 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event KeywordQueryEvent to "com.github.user0308.ulauncher-plugin-jump"
com.github.user0308.ulauncher-plugin-jump | 2018-12-14 15:53:31,057 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
path is None 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Client.py", line 52, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/bruno/.cache/ulauncher_cache/extensions/com.github.user0308.ulauncher-plugin-jump/main.py", line 29, in on_event
    query_result = List_choice().get_top_five(path)
  File "/home/bruno/.cache/ulauncher_cache/extensions/com.github.user0308.ulauncher-plugin-jump/list_choice.py", line 50, in get_top_five
    if path in record[0]:
TypeError: 'in <string>' requires string as left operand, not NoneType
2018-12-14 15:53:31,228 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 1 results
`

**Comment by ckp95** [comment]
Same here on Ubuntu 18.04.1. I can get results to show up if I manually set the directory to somewhere limited like ~/Documents, but when it searches from / it just hangs indefinitely. fd from the terminal finds stuff nearly instantly.
